//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.GenerateCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Contexts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Contexts()
        {
            this.Tb_Objects = new HashSet<Tb_Objects>();
        }
    
        public int ID_Context { get; set; }
        public int ID_Project { get; set; }
        public string ContextName { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Tb_Projects Tb_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Objects> Tb_Objects { get; set; }
    }
}
