//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.GenerateCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ResultSets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_ResultSets()
        {
            this.Tb_ResultSetColumns = new HashSet<Tb_ResultSetColumns>();
        }
    
        public int ID_ResultSet { get; set; }
        public int ID_Object { get; set; }
        public string ResultSetName { get; set; }
    
        public virtual Tb_Objects Tb_Objects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ResultSetColumns> Tb_ResultSetColumns { get; set; }
    }
}
