//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.GenerateCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ResultSetColumns
    {
        public int ID_ResultSetColumns { get; set; }
        public int ID_ResultSet { get; set; }
        public string ParameterName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Presition { get; set; }
        public bool Nullable { get; set; }
        public bool IsOut { get; set; }
    
        public virtual Tb_ResultSets Tb_ResultSets { get; set; }
    }
}
