//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.CodeGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Projects()
        {
            this.Tb_Contexts = new HashSet<Tb_Contexts>();
        }
    
        public int ID_Project { get; set; }
        public string ProjectName { get; set; }
        public string FileDirectory { get; set; }
        public string Server { get; set; }
        public string ProjectUser { get; set; }
        public string ProjectDatabase { get; set; }
        public string Password { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Contexts> Tb_Contexts { get; set; }
    }
}
