//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsAndExceptionsCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsAndExceptionsCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sensato.DataAccess.ErrorsAndExceptionsCatalog", typeof(ErrorsAndExceptionsCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 601.
        /// </summary>
        public static string _601_Code {
            get {
                return ResourceManager.GetString("601_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 601:  El procedimiento alamacenado o query está mal estructurado.&quot;.
        /// </summary>
        public static string _601_InvalidStoredProcedure {
            get {
                return ResourceManager.GetString("601_InvalidStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 602.
        /// </summary>
        public static string _602_Code {
            get {
                return ResourceManager.GetString("602_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 602:  El procedimiento almacenado o query tiene un valor indefinido o es nulo.&quot;.
        /// </summary>
        public static string _602_StoredProdecureNotFound {
            get {
                return ResourceManager.GetString("602_StoredProdecureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603.
        /// </summary>
        public static string _603_Code {
            get {
                return ResourceManager.GetString("603_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 603: El tipo de comando definido no es aceptable.&quot;.
        /// </summary>
        public static string _603_InvalidCommandType {
            get {
                return ResourceManager.GetString("603_InvalidCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 604.
        /// </summary>
        public static string _604_Code {
            get {
                return ResourceManager.GetString("604_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 604: El valor del tipo de comando no está definido o es nulo.&quot;.
        /// </summary>
        public static string _604_InvalidCommandType {
            get {
                return ResourceManager.GetString("604_InvalidCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 605.
        /// </summary>
        public static string _605_Code {
            get {
                return ResourceManager.GetString("605_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 605: La lista de parámetros no contiene la infomación requerida.&quot;.
        /// </summary>
        public static string _605_InvalidParameters {
            get {
                return ResourceManager.GetString("605_InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 606.
        /// </summary>
        public static string _606_Code {
            get {
                return ResourceManager.GetString("606_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 606: La lista de parámetros no está definida o su valor es nulo.&quot;.
        /// </summary>
        public static string _606_ParametersNotFound {
            get {
                return ResourceManager.GetString("606_ParametersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 607: Los datos proporcionados para hacer la conexión son incorrectos.&quot;.
        /// </summary>
        public static string _607__InvalidConnectionString {
            get {
                return ResourceManager.GetString("607_ InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 607.
        /// </summary>
        public static string _607_Code {
            get {
                return ResourceManager.GetString("607_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 608.
        /// </summary>
        public static string _608_Code {
            get {
                return ResourceManager.GetString("608_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 608: La cadena de conexión es indefinida o de valor nulo.&quot;.
        /// </summary>
        public static string _608_ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("608_ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 609.
        /// </summary>
        public static string _609_Code {
            get {
                return ResourceManager.GetString("609_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 609: El valor de la cadena de transacción es indefinido o de valor nulo.&quot;.
        /// </summary>
        public static string _609_SQLTransactionNotFound {
            get {
                return ResourceManager.GetString("609_SQLTransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 610.
        /// </summary>
        public static string _610_Code {
            get {
                return ResourceManager.GetString("610_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 610: Los valores contenidos dentro de la cadena son incorrectos.&quot;.
        /// </summary>
        public static string _610_InvalidSQLTransaction {
            get {
                return ResourceManager.GetString("610_InvalidSQLTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 611.
        /// </summary>
        public static string _611_Code {
            get {
                return ResourceManager.GetString("611_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 611: La conexión no pudo establecerse.&quot;.
        /// </summary>
        public static string _611_ConnectionNotEstablished {
            get {
                return ResourceManager.GetString("611_ConnectionNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 612.
        /// </summary>
        public static string _612_Code {
            get {
                return ResourceManager.GetString("612_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 612: La conexión fue cerrada.&quot;.
        /// </summary>
        public static string _612_ConnectionClosed {
            get {
                return ResourceManager.GetString("612_ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 612.
        /// </summary>
        public static string _613_Code {
            get {
                return ResourceManager.GetString("613_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 613: La tabla de datos no fue creada.&quot;.
        /// </summary>
        public static string _613_DataTableNotCreated {
            get {
                return ResourceManager.GetString("613_DataTableNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 614.
        /// </summary>
        public static string _614_Code {
            get {
                return ResourceManager.GetString("614_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 614: La colección de datos no fue creada.&quot;.
        /// </summary>
        public static string _614_DataSetNotCreated {
            get {
                return ResourceManager.GetString("614_DataSetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 615.
        /// </summary>
        public static string _615_Code {
            get {
                return ResourceManager.GetString("615_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 615: La sentencia no fue ejecutada.&quot;.
        /// </summary>
        public static string _615_SenteceNonExecuted {
            get {
                return ResourceManager.GetString("615_SenteceNonExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 616.
        /// </summary>
        public static string _616_Code {
            get {
                return ResourceManager.GetString("616_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 616: No se pudo obtener la tabla de datos.&quot;.
        /// </summary>
        public static string _616_InvalidDataTable {
            get {
                return ResourceManager.GetString("616_InvalidDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 617.
        /// </summary>
        public static string _617_Code {
            get {
                return ResourceManager.GetString("617_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 617: No se pudo obtener la colección de datos.&quot;.
        /// </summary>
        public static string _617_InvalidDataSet {
            get {
                return ResourceManager.GetString("617_InvalidDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 618.
        /// </summary>
        public static string _618_Code {
            get {
                return ResourceManager.GetString("618_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 618: No se pudo obtener el resultado de ejecución de la sentencia.&quot;.
        /// </summary>
        public static string _618_InvalidSentenceExecution {
            get {
                return ResourceManager.GetString("618_InvalidSentenceExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 619.
        /// </summary>
        public static string _619_Code {
            get {
                return ResourceManager.GetString("619_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 619: El comando no posee datos necesarios para poder ser ejecutado.&quot;.
        /// </summary>
        public static string _619_IncompleteCommand {
            get {
                return ResourceManager.GetString("619_IncompleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 620.
        /// </summary>
        public static string _620_Code {
            get {
                return ResourceManager.GetString("620_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 620: El valor del comando a ejecutar es nulo o no está definido.&quot;.
        /// </summary>
        public static string _620_InvalidCommand {
            get {
                return ResourceManager.GetString("620_InvalidCommand", resourceCulture);
            }
        }
    }
}
