//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsAndExceptionsCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsAndExceptionsCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sensato.DataAccess.ErrorsAndExceptionsCatalog", typeof(ErrorsAndExceptionsCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 601.
        /// </summary>
        public static string _601_Code {
            get {
                return ResourceManager.GetString("601_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 601:  El procedimiento alamacenado está mal estructurado..
        /// </summary>
        public static string _601_InvalidStoredProcedure {
            get {
                return ResourceManager.GetString("601_InvalidStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 602.
        /// </summary>
        public static string _602_Code {
            get {
                return ResourceManager.GetString("602_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 602:  El procedimiento almacenado tiene un valor indefinido o es nulo..
        /// </summary>
        public static string _602_StoredProdecureNotFound {
            get {
                return ResourceManager.GetString("602_StoredProdecureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603.
        /// </summary>
        public static string _603_Code {
            get {
                return ResourceManager.GetString("603_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 603: La Query está mal estructurada..
        /// </summary>
        public static string _603_InvalidQuery {
            get {
                return ResourceManager.GetString("603_InvalidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 604.
        /// </summary>
        public static string _604_Code {
            get {
                return ResourceManager.GetString("604_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 604: La Query no está definida o su valor es nulo..
        /// </summary>
        public static string _604_QueryNotFound {
            get {
                return ResourceManager.GetString("604_QueryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 605.
        /// </summary>
        public static string _605_Code {
            get {
                return ResourceManager.GetString("605_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 605: El tipo de comando no es aceptable..
        /// </summary>
        public static string _605_InvalidCommandType {
            get {
                return ResourceManager.GetString("605_InvalidCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 606: Los datos proporcionados para hacer la conexión son incorrectos..
        /// </summary>
        public static string _606__InvalidConnectionString {
            get {
                return ResourceManager.GetString("606_ InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 606.
        /// </summary>
        public static string _606_Code {
            get {
                return ResourceManager.GetString("606_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 607.
        /// </summary>
        public static string _607_Code {
            get {
                return ResourceManager.GetString("607_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 607: La cadena de conexión es indefinida o de valor nulo..
        /// </summary>
        public static string _607_ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("607_ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 608.
        /// </summary>
        public static string _608_Code {
            get {
                return ResourceManager.GetString("608_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 608: El valor de la cadena de transacción es indefinido o de valor nulo..
        /// </summary>
        public static string _608_SQLTransactionNotFound {
            get {
                return ResourceManager.GetString("608_SQLTransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 609.
        /// </summary>
        public static string _609_Code {
            get {
                return ResourceManager.GetString("609_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 609: No se pudo obtener la tabla de datos..
        /// </summary>
        public static string _609_InvalidDataTable {
            get {
                return ResourceManager.GetString("609_InvalidDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 610.
        /// </summary>
        public static string _610_Code {
            get {
                return ResourceManager.GetString("610_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 610: No se pudo obtener la colección de datos..
        /// </summary>
        public static string _610_InvalidDataSet {
            get {
                return ResourceManager.GetString("610_InvalidDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 611.
        /// </summary>
        public static string _611_Code {
            get {
                return ResourceManager.GetString("611_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 611: No se pudo obtener el resultado de ejecución de la sentencia..
        /// </summary>
        public static string _611_InvalidSentenceExecution {
            get {
                return ResourceManager.GetString("611_InvalidSentenceExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 612.
        /// </summary>
        public static string _612_Code {
            get {
                return ResourceManager.GetString("612_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 612: No se pudo establecer la conexión a la base de datos..
        /// </summary>
        public static string _612_ConnectionFailed {
            get {
                return ResourceManager.GetString("612_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 613.
        /// </summary>
        public static string _613_Code {
            get {
                return ResourceManager.GetString("613_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 613: Error no controlado..
        /// </summary>
        public static string _613_ErrorNotHandled {
            get {
                return ResourceManager.GetString("613_ErrorNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 614.
        /// </summary>
        public static string _614_Code {
            get {
                return ResourceManager.GetString("614_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 614: La lista de parámetros no está definida o su valor es nulo..
        /// </summary>
        public static string _614_ParametersNotFound {
            get {
                return ResourceManager.GetString("614_ParametersNotFound", resourceCulture);
            }
        }
    }
}
