//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorAndExceptionsCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorAndExceptionsCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sensato.Translate.ErrorAndExceptionsCatalog", typeof(ErrorAndExceptionsCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 701.
        /// </summary>
        public static string _701_Code {
            get {
                return ResourceManager.GetString("701_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 701: El valor del modelo no está definido o es nulo..
        /// </summary>
        public static string _701_ModelNotFound {
            get {
                return ResourceManager.GetString("701_ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 702.
        /// </summary>
        public static string _702_Code {
            get {
                return ResourceManager.GetString("702_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 702: La version del modelo es diferente a la requerida..
        /// </summary>
        public static string _702_InvalidVersionModel {
            get {
                return ResourceManager.GetString("702_InvalidVersionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 703.
        /// </summary>
        public static string _703_Code {
            get {
                return ResourceManager.GetString("703_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 703: El tipo de codificación proporcionada no es válida..
        /// </summary>
        public static string _703_InvalidEncoding {
            get {
                return ResourceManager.GetString("703_InvalidEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 704.
        /// </summary>
        public static string _704_Code {
            get {
                return ResourceManager.GetString("704_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 704: Modelo sin información necesaria para ser traducido..
        /// </summary>
        public static string _704_NotEnoughInformation {
            get {
                return ResourceManager.GetString("704_NotEnoughInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 705.
        /// </summary>
        public static string _705_Code {
            get {
                return ResourceManager.GetString("705_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 705: El nodo no fue creado..
        /// </summary>
        public static string _705_NotCreatedNode {
            get {
                return ResourceManager.GetString("705_NotCreatedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 706: El nodo señalado no contiene elementos en su interior..
        /// </summary>
        public static string _706_ChildNodesNotFound {
            get {
                return ResourceManager.GetString("706_ChildNodesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 706.
        /// </summary>
        public static string _706_Code {
            get {
                return ResourceManager.GetString("706_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 707: El valor asignado al atributo es nulo o indefinido..
        /// </summary>
        public static string _707_AttributeValueNotFound {
            get {
                return ResourceManager.GetString("707_AttributeValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 707.
        /// </summary>
        public static string _707_Code {
            get {
                return ResourceManager.GetString("707_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 708.
        /// </summary>
        public static string _708_Code {
            get {
                return ResourceManager.GetString("708_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 708: El nodo es inexistente, o posee otro nombre..
        /// </summary>
        public static string _708_InvalidSingleNodeSelected {
            get {
                return ResourceManager.GetString("708_InvalidSingleNodeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 709.
        /// </summary>
        public static string _709_Code {
            get {
                return ResourceManager.GetString("709_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 709: El nombre de la clase principlal tiene un valor nulo o no definido..
        /// </summary>
        public static string _709_MainClassNameNotFound {
            get {
                return ResourceManager.GetString("709_MainClassNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 710.
        /// </summary>
        public static string _710_Code {
            get {
                return ResourceManager.GetString("710_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 710: El nombre de la clase principal no puede contener caracteres especiales..
        /// </summary>
        public static string _710_MainClassInvalidName {
            get {
                return ResourceManager.GetString("710_MainClassInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 711.
        /// </summary>
        public static string _711_Code {
            get {
                return ResourceManager.GetString("711_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 711: Es requerido que todos los métodos sean requeridos con un nombre..
        /// </summary>
        public static string _711_NameMethodNotFound {
            get {
                return ResourceManager.GetString("711_NameMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 712.
        /// </summary>
        public static string _712_Code {
            get {
                return ResourceManager.GetString("712_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 712: Los datos no fueron traducidos a lenguaje XML..
        /// </summary>
        public static string _712_DocumentFormatNotCreated {
            get {
                return ResourceManager.GetString("712_DocumentFormatNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 713.
        /// </summary>
        public static string _713_Code {
            get {
                return ResourceManager.GetString("713_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 713: El constructor no contiene un nombre de clase..
        /// </summary>
        public static string _713_NameClassNotFound {
            get {
                return ResourceManager.GetString("713_NameClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 714.
        /// </summary>
        public static string _714_Code {
            get {
                return ResourceManager.GetString("714_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 714: El nombre de la clase no debe contener caracteres especiales..
        /// </summary>
        public static string _714_StrangeCharacterInClassName {
            get {
                return ResourceManager.GetString("714_StrangeCharacterInClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 715: El método especificado no retorna un valor..
        /// </summary>
        public static string _715__ValueIsNotReturnedInMethod {
            get {
                return ResourceManager.GetString("715_ ValueIsNotReturnedInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 715.
        /// </summary>
        public static string _715_Code {
            get {
                return ResourceManager.GetString("715_Code", resourceCulture);
            }
        }
    }
}
