//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensato.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorAndExceptionsCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorAndExceptionsCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sensato.Translate.ErrorAndExceptionsCatalog", typeof(ErrorAndExceptionsCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 701: El modelo proporcionado no contiene datos tipo XML.&quot;.
        /// </summary>
        public static string _701_InvalidTypeModel {
            get {
                return ResourceManager.GetString("701_InvalidTypeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 702: El valor del modelo no está definido o es nulo.&quot;.
        /// </summary>
        public static string _702_ModelNotFound {
            get {
                return ResourceManager.GetString("702_ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 703: La version del modelo es diferente a la requerida.&quot;.
        /// </summary>
        public static string _703_InvalidVersionModel {
            get {
                return ResourceManager.GetString("703_InvalidVersionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 704: El tipo de codificación proporcionada no es válida.&quot;.
        /// </summary>
        public static string _704_InvalidEncoding {
            get {
                return ResourceManager.GetString("704_InvalidEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 705: El modelo no contiene el dato solicitado.&quot;.
        /// </summary>
        public static string _705_ElementNotFound {
            get {
                return ResourceManager.GetString("705_ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 706: El nodo no fue creado.&quot;.
        /// </summary>
        public static string _706_NotCreatedNode {
            get {
                return ResourceManager.GetString("706_NotCreatedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 707: El nodo no fue insertado en el nivel especificado.&quot;.
        /// </summary>
        public static string _707_AppendNodeFailed {
            get {
                return ResourceManager.GetString("707_AppendNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 708: El/los atributos no fueron agregados al nodo.&quot;.
        /// </summary>
        public static string _708_AttributesFailed {
            get {
                return ResourceManager.GetString("708_AttributesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 709: El elemento al que se está apuntando no tiene esa propiedad.&quot;.
        /// </summary>
        public static string _709_InvalidProperty {
            get {
                return ResourceManager.GetString("709_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 710: El nodo señalado no contiene elementos en su interior.&quot;.
        /// </summary>
        public static string _710_ChildNodesNotFound {
            get {
                return ResourceManager.GetString("710_ChildNodesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 711: El valor asignado al atributo no coincide con los aceptados.&quot;.
        /// </summary>
        public static string _711_InvalidAttributeValue {
            get {
                return ResourceManager.GetString("711_InvalidAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 712: El valor asignado al atributo es nulo o indefinido.&quot;.
        /// </summary>
        public static string _712_AttributeValueNotFound {
            get {
                return ResourceManager.GetString("712_AttributeValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 713: No se pudo insertar el texto en la etiqueta.&quot;.
        /// </summary>
        public static string _713_NodeTextError {
            get {
                return ResourceManager.GetString("713_NodeTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 714: La etiqueta a la que se hace referencia no contiene texto.&quot;.
        /// </summary>
        public static string _714_NodeTextNotFound {
            get {
                return ResourceManager.GetString("714_NodeTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 715: El nodo es inexistente, o posee otro nombre.&quot;.
        /// </summary>
        public static string _715_InvalidSingleNodeSelected {
            get {
                return ResourceManager.GetString("715_InvalidSingleNodeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 716: Los nodos con el nombre especificado son inexistentes o tiene un nombre distinto.&quot;.
        /// </summary>
        public static string _716_InvalidNodesSelected {
            get {
                return ResourceManager.GetString("716_InvalidNodesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 717: El nodo no contiene la propiedad especificada o tiene otro nombre.&quot;.
        /// </summary>
        public static string _717_InvalidNodeProperty {
            get {
                return ResourceManager.GetString("717_InvalidNodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 718: Los argumentos dados son incorrectos.&quot;.
        /// </summary>
        public static string _718_InvalidTemplateArguments {
            get {
                return ResourceManager.GetString("718_InvalidTemplateArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 719: Los datos no fueron traducidos a lenguaje XML.&quot;.
        /// </summary>
        public static string _719_DocumentFormatNotCreated {
            get {
                return ResourceManager.GetString("719_DocumentFormatNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error 720: El valor asignado no coincide con el tipo de dato requerido.&quot;.
        /// </summary>
        public static string _720_InvalidValueAssignment {
            get {
                return ResourceManager.GetString("720_InvalidValueAssignment", resourceCulture);
            }
        }
    }
}
